version: '3.7'
services:
    financing-commands:
        build: 
          context: .
          dockerfile: ./build/commandsd/Dockerfile
        restart: always    
        ports:
          - "8080:8080"
        environment:
          - WAIT=2000
          - SERVER_ADDRESS=0.0.0.0:8080
          - LOGGER_LEVEL=INFO
          - DB_CONNECTION_STRING=user=postgres password=postgres host=postgres port=5432 dbname=postgres pool_max_conns=10
          - AMQP_ADDRESS=amqp://guest:guest@rabbitmq:5672/
        depends_on:
          - postgres
          - rabbitmq

    financing-relayer:
        build: 
          context: .
          dockerfile: ./build/relayerd/Dockerfile
        restart: always
        environment:
          - WAIT=2000
          - LOGGER_LEVEL=INFO
          - DB_CONNECTION_STRING=user=postgres password=postgres host=postgres port=5432 dbname=postgres pool_max_conns=10
          - AMQP_ADDRESS=amqp://guest:guest@rabbitmq:5672/
        depends_on:
          - postgres
          - rabbitmq

    postgres:
        image: postgres
        restart: always
        environment: 
          - POSTGRES_HOST=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes:
          - ./build/volumes/postgres-data:/var/lib/postgresql/data
          - ./build/postgres:/docker-entrypoint-initdb.d

    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: 'rabbitmq'
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
          - ./build/volumes/rabbitmq/data/:/var/lib/rabbitmq/
          - ./build/volumes/rabbitmq/log/:/var/log/rabbitmq