// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.18.0
// source: api/command.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SellInvoiceCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuerId    *UUID  `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	AskingPrice *Money `protobuf:"bytes,2,opt,name=asking_price,json=askingPrice,proto3" json:"asking_price,omitempty"`
}

func (x *SellInvoiceCommand) Reset() {
	*x = SellInvoiceCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellInvoiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInvoiceCommand) ProtoMessage() {}

func (x *SellInvoiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInvoiceCommand.ProtoReflect.Descriptor instead.
func (*SellInvoiceCommand) Descriptor() ([]byte, []int) {
	return file_api_command_proto_rawDescGZIP(), []int{0}
}

func (x *SellInvoiceCommand) GetIssuerId() *UUID {
	if x != nil {
		return x.IssuerId
	}
	return nil
}

func (x *SellInvoiceCommand) GetAskingPrice() *Money {
	if x != nil {
		return x.AskingPrice
	}
	return nil
}

type BidOnInvoiceCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvestorId *UUID  `protobuf:"bytes,1,opt,name=investor_id,json=investorId,proto3" json:"investor_id,omitempty"`
	InvoiceId  *UUID  `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Bid        *Money `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *BidOnInvoiceCommand) Reset() {
	*x = BidOnInvoiceCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidOnInvoiceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidOnInvoiceCommand) ProtoMessage() {}

func (x *BidOnInvoiceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidOnInvoiceCommand.ProtoReflect.Descriptor instead.
func (*BidOnInvoiceCommand) Descriptor() ([]byte, []int) {
	return file_api_command_proto_rawDescGZIP(), []int{1}
}

func (x *BidOnInvoiceCommand) GetInvestorId() *UUID {
	if x != nil {
		return x.InvestorId
	}
	return nil
}

func (x *BidOnInvoiceCommand) GetInvoiceId() *UUID {
	if x != nil {
		return x.InvoiceId
	}
	return nil
}

func (x *BidOnInvoiceCommand) GetBid() *Money {
	if x != nil {
		return x.Bid
	}
	return nil
}

type ApproveFinancingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId *UUID `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
}

func (x *ApproveFinancingCommand) Reset() {
	*x = ApproveFinancingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveFinancingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveFinancingCommand) ProtoMessage() {}

func (x *ApproveFinancingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveFinancingCommand.ProtoReflect.Descriptor instead.
func (*ApproveFinancingCommand) Descriptor() ([]byte, []int) {
	return file_api_command_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveFinancingCommand) GetInvoiceId() *UUID {
	if x != nil {
		return x.InvoiceId
	}
	return nil
}

type ReverseFinancingCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvoiceId *UUID `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
}

func (x *ReverseFinancingCommand) Reset() {
	*x = ReverseFinancingCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseFinancingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseFinancingCommand) ProtoMessage() {}

func (x *ReverseFinancingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseFinancingCommand.ProtoReflect.Descriptor instead.
func (*ReverseFinancingCommand) Descriptor() ([]byte, []int) {
	return file_api_command_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseFinancingCommand) GetInvoiceId() *UUID {
	if x != nil {
		return x.InvoiceId
	}
	return nil
}

var File_api_command_proto protoreflect.FileDescriptor

var file_api_command_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x12, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x09, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x29, 0x0a, 0x0c, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x0b, 0x61,
	0x73, 0x6b, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x7d, 0x0a, 0x13, 0x42, 0x69,
	0x64, 0x4f, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x26, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x0a, 0x69,
	0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0a, 0x69, 0x6e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x52, 0x03, 0x62, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x17, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52,
	0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x17, 0x52, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0a, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x49, 0x64, 0x32, 0xff, 0x01, 0x0a, 0x08,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x0b, 0x53, 0x65, 0x6c, 0x6c,
	0x49, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x6e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x05, 0x2e, 0x55,
	0x55, 0x49, 0x44, 0x12, 0x3c, 0x0a, 0x0c, 0x42, 0x69, 0x64, 0x4f, 0x6e, 0x49, 0x6e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x42, 0x69, 0x64, 0x4f, 0x6e, 0x49, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x44, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6e, 0x61,
	0x6e, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46,
	0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x10, 0x52, 0x65, 0x76, 0x65, 0x72,
	0x73, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x52, 0x65,
	0x76, 0x65, 0x72, 0x73, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x10, 0x5a,
	0x0e, 0x2e, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_command_proto_rawDescOnce sync.Once
	file_api_command_proto_rawDescData = file_api_command_proto_rawDesc
)

func file_api_command_proto_rawDescGZIP() []byte {
	file_api_command_proto_rawDescOnce.Do(func() {
		file_api_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_command_proto_rawDescData)
	})
	return file_api_command_proto_rawDescData
}

var file_api_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_command_proto_goTypes = []interface{}{
	(*SellInvoiceCommand)(nil),      // 0: SellInvoiceCommand
	(*BidOnInvoiceCommand)(nil),     // 1: BidOnInvoiceCommand
	(*ApproveFinancingCommand)(nil), // 2: ApproveFinancingCommand
	(*ReverseFinancingCommand)(nil), // 3: ReverseFinancingCommand
	(*UUID)(nil),                    // 4: UUID
	(*Money)(nil),                   // 5: Money
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_api_command_proto_depIdxs = []int32{
	4,  // 0: SellInvoiceCommand.issuer_id:type_name -> UUID
	5,  // 1: SellInvoiceCommand.asking_price:type_name -> Money
	4,  // 2: BidOnInvoiceCommand.investor_id:type_name -> UUID
	4,  // 3: BidOnInvoiceCommand.invoice_id:type_name -> UUID
	5,  // 4: BidOnInvoiceCommand.bid:type_name -> Money
	4,  // 5: ApproveFinancingCommand.invoice_id:type_name -> UUID
	4,  // 6: ReverseFinancingCommand.invoice_id:type_name -> UUID
	0,  // 7: Commands.SellInvoice:input_type -> SellInvoiceCommand
	1,  // 8: Commands.BidOnInvoice:input_type -> BidOnInvoiceCommand
	2,  // 9: Commands.ApproveFinancing:input_type -> ApproveFinancingCommand
	3,  // 10: Commands.ReverseFinancing:input_type -> ReverseFinancingCommand
	4,  // 11: Commands.SellInvoice:output_type -> UUID
	6,  // 12: Commands.BidOnInvoice:output_type -> google.protobuf.Empty
	6,  // 13: Commands.ApproveFinancing:output_type -> google.protobuf.Empty
	6,  // 14: Commands.ReverseFinancing:output_type -> google.protobuf.Empty
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_command_proto_init() }
func file_api_command_proto_init() {
	if File_api_command_proto != nil {
		return
	}
	file_api_financing_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellInvoiceCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidOnInvoiceCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveFinancingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReverseFinancingCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_command_proto_goTypes,
		DependencyIndexes: file_api_command_proto_depIdxs,
		MessageInfos:      file_api_command_proto_msgTypes,
	}.Build()
	File_api_command_proto = out.File
	file_api_command_proto_rawDesc = nil
	file_api_command_proto_goTypes = nil
	file_api_command_proto_depIdxs = nil
}
