// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.0
// source: api/query.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueriesClient is the client API for Queries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueriesClient interface {
	AllInvestors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllInvestorsReply, error)
	AllInvoices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllInvoicesReply, error)
	AllIssuers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllIssuersReply, error)
}

type queriesClient struct {
	cc grpc.ClientConnInterface
}

func NewQueriesClient(cc grpc.ClientConnInterface) QueriesClient {
	return &queriesClient{cc}
}

func (c *queriesClient) AllInvestors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllInvestorsReply, error) {
	out := new(AllInvestorsReply)
	err := c.cc.Invoke(ctx, "/Queries/AllInvestors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queriesClient) AllInvoices(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllInvoicesReply, error) {
	out := new(AllInvoicesReply)
	err := c.cc.Invoke(ctx, "/Queries/AllInvoices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queriesClient) AllIssuers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AllIssuersReply, error) {
	out := new(AllIssuersReply)
	err := c.cc.Invoke(ctx, "/Queries/AllIssuers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueriesServer is the server API for Queries service.
// All implementations must embed UnimplementedQueriesServer
// for forward compatibility
type QueriesServer interface {
	AllInvestors(context.Context, *emptypb.Empty) (*AllInvestorsReply, error)
	AllInvoices(context.Context, *emptypb.Empty) (*AllInvoicesReply, error)
	AllIssuers(context.Context, *emptypb.Empty) (*AllIssuersReply, error)
	mustEmbedUnimplementedQueriesServer()
}

// UnimplementedQueriesServer must be embedded to have forward compatible implementations.
type UnimplementedQueriesServer struct {
}

func (UnimplementedQueriesServer) AllInvestors(context.Context, *emptypb.Empty) (*AllInvestorsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllInvestors not implemented")
}
func (UnimplementedQueriesServer) AllInvoices(context.Context, *emptypb.Empty) (*AllInvoicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllInvoices not implemented")
}
func (UnimplementedQueriesServer) AllIssuers(context.Context, *emptypb.Empty) (*AllIssuersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllIssuers not implemented")
}
func (UnimplementedQueriesServer) mustEmbedUnimplementedQueriesServer() {}

// UnsafeQueriesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueriesServer will
// result in compilation errors.
type UnsafeQueriesServer interface {
	mustEmbedUnimplementedQueriesServer()
}

func RegisterQueriesServer(s grpc.ServiceRegistrar, srv QueriesServer) {
	s.RegisterService(&Queries_ServiceDesc, srv)
}

func _Queries_AllInvestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueriesServer).AllInvestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queries/AllInvestors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueriesServer).AllInvestors(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queries_AllInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueriesServer).AllInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queries/AllInvoices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueriesServer).AllInvoices(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Queries_AllIssuers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueriesServer).AllIssuers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Queries/AllIssuers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueriesServer).AllIssuers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Queries_ServiceDesc is the grpc.ServiceDesc for Queries service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Queries_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Queries",
	HandlerType: (*QueriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllInvestors",
			Handler:    _Queries_AllInvestors_Handler,
		},
		{
			MethodName: "AllInvoices",
			Handler:    _Queries_AllInvoices_Handler,
		},
		{
			MethodName: "AllIssuers",
			Handler:    _Queries_AllIssuers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/query.proto",
}
